### ISSUE TITLE
False Positives for Geofence when Location Estimation is very bad

### ISSUE THREAD

**Issue by Lenzebo** [owntracks/ios#76] opened 2014-07-19 06:16 UTC
Problem: On my way home from work, when i am in the subway, suddenly my _"Home"_ waypoint triggers an "Enter" Event, although I am still some kilometers away. I think this might be of a very bad location estimate of iOS with a uncertainty radius with some kilometers.
Here http://mobileoop.com/ios-region-monitoring-and-location-manager is a description of the problem and a possible workaround for this issue.

**Comment by dtriphaus** [comment] 2015-01-27 09:50
Maybe it is possible to have a configuration option to ignore locations with a bad accuracy (config param in m)? So everyone can configure what to ignore (accuracy worse than 1000m or whatever.

**Comment by ckrey** [comment] 2015-02-25 10:22
Dear @dtriphaus,

as far as I know there is no configuration option for enter/leave events which are generated by IOS.
Filtering them out by the application would mean that no enter event is published at all.

**Comment by markus0m** [comment] 2015-08-18 13:53
I'm having the same problem, making it impossible for me to use regions at all.

iPhone 5s, iOS 8.4, v8.2.11
wp1: Home zone, r:100m
wp2: Office zone, r:400m
The distance between wp1 and wp2 is roughly 3km.

When I turn off Wi-Fi at the office, wp1 region shows as active after some time.
Turning it back on immediately deactivates wp1 and fires a leave event.
Office region wp2 is active throughout.

Please try to find a workaround for this problem.

**Comment by ckrey** [comment] 2015-08-18 16:11
Can you tell which coordinates and accuracy are displayed with Wifi on / off? Hit the (i) button.
Are the locations reported correct in both cases?

**Comment by markus0m** [comment] 2015-08-18 16:25
Locations are reported correctly and show an accuracy of 10m right now. 
I'm currently on the move in a bus but still my home region started showing up as active shortly after disabling Wi-Fi.

**Comment by ckrey** [comment] 2015-08-18 16:33
I am not sure if I understand you right:
a) what do you mean by activate/deactivate (coloring of regions on map? coloring of symbols in regions?, transition events sent via MQTT?)
b) can you send me a direct message with the publishes send from the phone (location and transition)?

**Comment by markus0m** [comment] 2015-08-18 16:54
Coloring of symbols in the regions tab of the app.
I am mostly not getting notifications in the app for entering false positives (would have said none but it just happened). 
Some time during a subway ride the office zone deactivated but went active again (without a notification) as soon as I had GPS reception again.
Turning Wi-Fi back on instantly deactivated both zones (with notifications).
I first noticed the whole problem when I would get random "Leaving Office Zone" notifications at home while I had Wi-Fi disabled.

MQTT is not set up to receive events right now.
I'll log them for a day or two and send you the results.

**Comment by ckrey** [comment] 2015-08-20 07:54
I was successful reproducing the problem:

iOS reports a region enter event when switching off Wifi and cannot determine the location because no GPS.

I do not re-check and ignore incorrect enter/leave events and correct false region state reports.

The two regions below are a few kilometers apart:
![img_4256](https://cloud.githubusercontent.com/assets/4027289/9378383/573a2734-4721-11e5-9ac1-1b9131472489.PNG)

**Comment by markus0m** [comment] 2015-08-20 19:31
Wow, faster than my bug report :)
If you still need my log from today I can send it to you.
Any chance I can get into your iOS beta program?

**Comment by ckrey** [comment] 2015-08-21 07:37
No, I don't think I need another report. I will try to log a bug with Apple.

No problem, just send me your email-address, you'll be invited to Testflight and will receive the beta of the next App Store release candidate when ready

**Comment by ckrey** [comment] 2015-08-27 19:51
correctly detects false positives when entering, but not when leaving circular region

**Comment by ckrey** [comment] 2015-08-27 19:51
fixed

**Comment by ckrey** [comment] 2015-10-22 09:06
The fix does now suppresses too many enter/leave events

**Comment by matbor** [comment] 2015-10-22 09:40
Will update tmr if it fixes it ;)

**Comment by matbor** [comment] 2015-10-22 23:35
@ckrey 8.4.5 Seems to of fixed my issue, reported all waypoints enter/leave. Let me know if you want me to email you the data again for you to dbl chk.

**Comment by ckrey** [comment] 2015-10-23 10:56
@matbor no thanks, not necessary

**Comment by matbor** [comment] 2015-10-24 06:58
@ckrey Seems a bit flaky again. Will send you the logs. I hadn't updated to 8.4.6, but was running iOS 9.1

**Comment by rjp** [comment] 2017-02-20 12:29
Can confirm this does still happen - I've had it say "in, out, in" whilst near the border of my 400m geofences. A generic setting for "ignore all locations with error > Xm" would be helpful for this (and other situations - I never want anything logged with error > 350m, for example.)

**Comment by ckrey** [comment] 2021-12-21 12:29
Closing this issue as we did not hear anything new sincd 2017 ( iOS 9)

**Closed by ckrey** 2021-12-21 12:29 UTC
Labels: bug
