### ISSUE TITLE
Trouble connecting after a day or two

### ISSUE THREAD

**Issue by matbor** [owntracks/ios#742] opened 2023-06-16 13:46 UTC
Hi team, I have 3x ios16.5 devices running Owntracks 16.4.1 and 2x of them seem to work fine, as they are used a lot, but one of my other devices that doesn’t leave the house that often has trouble connecting if it hasn’t been touched for a few days. 

Running tls with client certificates.

mosquito logs

```
1680839866: mosquitto version 2.0.15 running

58056-1686917077: New connection from 180.xxx.xxx.xxx:50279 on port 8883.
58057-1686917077: OpenSSL Error[0]: error:14FFF0C7:SSL routines:(UNKNOWN)SSL_internal:peer did not return a certificate
58058-1686917077: Client <unknown> disconnected: Protocol error.
58059-1686917078: New connection from 180.xxx.xxx.xxx:50280 on port 8883.
58060-1686917078: OpenSSL Error[0]: error:14FFF0C7:SSL routines:(UNKNOWN)SSL_internal:peer did not return a certificate
58061-1686917078: Client <unknown> disconnected: Protocol error.
58062-1686918030: New connection from 180.xxx.xxx.xxx:50305 on port 8883.
58063-1686918030: OpenSSL Error[0]: error:14FFF0C7:SSL routines:(UNKNOWN)SSL_internal:peer did not return a certificate
58064-1686918030: Client <unknown> disconnected: Protocol error.
58065-1686918030: New connection from 180.xxx.xxx.xxx:50308 on port 8883.
58066-1686918031: OpenSSL Error[0]: error:14FFF0C7:SSL routines:(UNKNOWN)SSL_internal:peer did not return a certificate
58067-1686918031: Client <unknown> disconnected: Protocol error.
58068-1686918032: New connection from 180.xxx.xxx.xxx:50316 on port 8883.
58069-1686918032: OpenSSL Error[0]: error:14FFF0C7:SSL routines:(UNKNOWN)SSL_internal:peer did not return a certificate
58070-1686918032: Client <unknown> disconnected: Protocol error.
58071-1686918034: New connection from 180.xxx.xxx.xxx:50328 on port 8883.
58072-1686918034: OpenSSL Error[0]: error:14FFF0C7:SSL routines:(UNKNOWN)SSL_internal:peer did not return a certificate
58073-1686918034: Client <unknown> disconnected: Protocol error.
58074:1686918038: New connection from 180.xxx.xxx.xxx:50335 on port 8883.
58075:1686918038: OpenSSL Error[0]: error:14FFF0C7:SSL routines:(UNKNOWN)SSL_internal:peer did not return a certificate
58076:1686918038: Client <unknown> disconnected: Protocol error.
```

In the owntracks app, it keeps going from idle to connecting, don’t really see any error.

However, after killing the app, ie. swipe up, the app reconnects fine and uploads all the cached mqtt messages. Will then switch fine between 4g/wifi

Logs after killing app.
```
58077-1686918046: New connection from 180.xxx.xxx.xxx:50341 on port 8883.
58078-1686918046: New client connected from 180.xxx.xxx.xxx:50341 as FRED (p2, c0, k60, u'FRED').
58079-1686918057: Client FRED disconnected
```

Let me know if you need anymore details.

**Comment by ckrey** [comment] 2023-06-17 05:34
@matbor thank you for reporting the issue. The problem is known since #605. We are using Apple's NSURLSession do connect and re-connect. Up to now we have not found a solution for the problem.

**Comment by matbor** [comment] 2023-06-20 10:52
@ckrey thanks for that, I did find those similar issues, but noticed they had stalled.

Where you able to replicate this on your devices?

**Comment by ckrey** [comment] 2024-03-19 16:31
Sorry, we have no new insight to the problem. Will close this issue, but leave #605 open

**Closed by ckrey** 2024-03-19 16:31 UTC
Labels: bug
