### ISSUE TITLE
IOS 11.0.1 forgets location services setting for Owntracks

### ISSUE THREAD

**Issue by x821938** [owntracks/ios#486] opened 2017-10-01 19:36 UTC
Hi,

Since I upgraded to IOS 11.0.1 owntrack doesn't publish location data anymore.

It has a strange behaviour in "settings->privacy->location services->owntrack" You can see a screen recording here: [https://www.offline.dk/misc/owntracks.mp4](https://www.offline.dk/misc/owntracks.mp4)

Every time owntrack is closed. IOS forgets the location setting.
I hope this makes sense.

Best regards,
   Alex

**Comment by davebv** [comment] 2017-10-01 22:24
I observed the same behavior. And cannot update location since updated to iOS 11.0.1

**Comment by bachya** [comment] 2017-10-01 22:52
This is already being tracked in #483.

**Comment by schettada** [comment] 2017-10-02 15:37
Same here as well. But i dont think it has to to do with 11.0.1. I'm running 11.0 and it was working as expected. Seeing this issue after the owntracks app update to version 9.7.1. I was running ios 11 beta as well and didnt see the issue.

**Comment by ckrey** [comment] 2017-10-02 16:15
The issue is known and tracked in #483. It is fixed and uploaded to Apple, hoping for their App Store team to begin their new week.

The old 9.6.x version did work on iOS11 as long as you did not install it from scratch. 9.7.1 fixed another iOS11 related problem regarding the address book (#481).

Unfortunately, it did not fully implement the new semantics for background location usage in iOS11.

I do close this issue now because it is a duplicate of #483

**Closed by ckrey** 2017-10-02 16:15 UTC

**Comment by davebv** [comment] 2017-10-04 17:10
thanks, after updating to 9.7.2, location is reported correctly again.

**Comment by ckrey** [comment] 2017-10-04 17:12
Good to hear!

**Comment by x821938** [comment] 2017-10-05 16:14
Same here :) thanks :)
