### ISSUE TITLE
kCLErrorDomain 2

### ISSUE THREAD

**Issue by duiffie** [owntracks/ios#539] opened 2018-06-15 14:44 UTC
When I go to the friends tab, I now see an error saying:

> Address resolver failed
> kCLErrorDomain 2
> due to rate limit or off-line

instead of the actual address. Location data seems accurate, but the address could not be resolved. Anything wrong on my device or with the app? I'm currently using version 9.9.3

**Comment by mg0536** [comment] 2018-06-26 13:50
Me too. Not sure if this is a bug.  If not, this issue could be documented, with perhaps a configuration space fix.

![img_4596](https://user-images.githubusercontent.com/40570650/41916527-3bc83948-7926-11e8-8562-d7497c87c425.PNG)

**Comment by jpmens** [comment] 2018-06-26 14:00
That is not a bug, it is exactly what it says: "due to rate-limiting or offline". The position has been transferred, but your device is just not showing the reverse-geo lookup.

**Comment by ckrey** [comment] 2018-06-26 15:37
The Rate Limit is set by iOS. We saw this happening quite often after an iOS update. Please try to restart the device.

> iOS throttles CLGeocoder requests, it varies but generally allows 50 or so requests at a time. The time period is an unknown.

**Closed** 2018-06-26 15:38 UTC
