### ISSUE TITLE
Geofence enter/leave events frequently not published

### ISSUE THREAD

**Issue by cpcowart** [owntracks/ios#375] opened 2016-02-05 19:52 UTC
At least 1/4 times I enter or leave my geofenced region, the event does not get published. This is probably in part due to the geofenced area having somewhat poor cell reception.

Generally, I see a red notification icon on the app indicating that the event is queued. Upon launching the app with a queued notification, the message eventually disappears from the Messaging view but never appears on the mqtt server.

When I first began using Owntracks, these queued messages were always reliably sent after opening the app. Sometime in the last 6 months or so, they became very unreliable.

I'm on the latest iOS release running Owntracks 8.3.3.

Let me know if there's any additional debugging information I can provide.

Thanks!

**Comment by jpmens** [comment] 2016-02-05 19:56
It is unlikely that messages _get lost_; transition events as with other messages are quite reliably queued and delivered. You say "during the last.6 months or so" the reliability has suffered. Can you tell us which kind of MQTT broker you are using (private, publiic, etc) and if possible its version. 

FYI, a new version of our iOS app is on the way to the app store as we speak (though I cannot say when it'll appear as that is beyond our control).

**Comment by cpcowart** [comment] 2016-02-05 20:34
I'm running a private instance of mosquitto 1.4.4.

I continuously leave mosquitto_sub running, but I do not see the leave event published to the queue. When I open Owntracks, the queue stays quiet, the red notification indicator disappears, and the queued message disappears without ever showing up on the queue.

For example:

owntracks/chris/event {"t":"c","tst":1454652034,"acc":5,"_type":"transition","event":"enter","lon":-122.X,"lat":37.Y,"wtst":1447392495,"tid":"IS","desc":"pcl"}
owntracks/chris {"cog":46,"batt":82,"lon":-122.X,"acc":5,"p":102.7270584106445,"vel":80,"vac":4,"lat":37.Y,"t":"c","tst":1454652034,"alt":6,"_type":"location","tid":"IS"}
owntracks/chris/event {"t":"c","tst":1454652048,"acc":5,"_type":"transition","event":"leave","lon":-122.X,"lat":37.Y,"wtst":1447392495,"tid":"IS","desc":"pcl"}
owntracks/chris {"cog":47,"batt":82,"lon":-122.X,"acc":5,"p":102.7467651367188,"vel":79,"vac":3,"lat":37.Y,"t":"c","tst":1454652048,"alt":4,"_type":"location","tid":"IS"}
owntracks/chris/event {"t":"c","tst":1454653521,"acc":5,"_type":"transition","event":"enter","lon":-122.X,"lat":37.Y,"wtst":1447392495,"tid":"IS","desc":"pcl"}
owntracks/chris {"cog":306,"batt":87,"lon":-122.X,"acc":5,"p":102.7480163574219,"vel":40,"vac":3,"lat":37.Y,"t":"c","tst":1454653521,"alt":0,"_type":"location","tid":"IS"}
owntracks/chris {"tst":"1454656256","_type":"lwt"}

This is the end of the queue. There was a leave event this morning (I got the notification banner on my phone, I saw a red notification icon on the app, I launched the app and saw the event queued on the Messages view). But the queue never received the event. It's just not there. **It is lost.**

**Comment by ckrey** [comment] 2016-02-11 08:17
`owntracks/chris {"tst":"1454656256","_type":"lwt"}` indicates the app has either crashed or was 'swiped out'. I'll check if I see any crash report in iTunes connect.

**Comment by bdleedy** [comment] 2016-12-20 00:46
I am suffering from this as well. I currently have 66 items awaiting publishing (I assume waiting for permission from iOS to use the internet connection). I use significant move mode. I have a private mosquitto server and see no errors on it. It seems like when the app drops beyond the top five apps in the background, it looses this access to connectivity. I've tried to clear my background apps and 'pull the app forward in the queue' without opening it and it did not help. I brought it all the way to the first background app and no change. Once I open the app though, it will immediately vomit all of the data onto my server, without error.

What can I provide to help with this issue?

**Comment by ckrey** [comment] 2016-12-20 07:47
If the messages queue up as indicated with the badge on the app icon, the app could not transfer the messages while in background.

The app is woken up on a enter/leave event and regularly about every 15 minutes. But the time available to connect and send the queued messages is limited by iOS. If the cell network is poor it may take longer than the time slot (10 sec) to establish the connection. If you are using TLS (recommended) the handshake between app and broker is significant.

The position of OwnTracks in the background "queue" as you call it is not relevant. You cannot influence the iOS scheduler by modifying the "queue".

**Comment by bdleedy** [comment] 2016-12-20 11:25
So at what point will it send them? I can't think of an area where I have poor cell signal between here and work. I am using TLS. Also, wouldn't it eventually wake up and attempt the send while on wifi once I'm home or at work? PLUS, when I eventually open the app, it won't take nearly 10 seconds to send that data. I can watch the server and see it all come in within that amount of time.

**Comment by bdleedy** [comment] 2016-12-20 11:27
I have turned off wifi so that I am not changing to/from it when leaving/entering. I will see if that changes the results today.

**Comment by jpmens** [comment] 2016-12-20 11:28
It will attempt whenever the app has connectivity, and you ought to be able to see that broker-side. You say "it won't take nearly 10 secs" by which I think this is taking far too long.

Do you have a firewall between the phone and your broker? 
Can you test from "outside" your broker's network with a simple `mosquitto_sub -d` or something how long the connection takes?

Turning off Wifi will not typically help (unless you *know* that the Wifi network won't find your broker).

**Comment by jpmens** [comment] 2016-12-20 11:30
You write:

> I can watch the server and see it all come in within that amount of time

Please check the Mosquitto logs: you'll see the connection and then the publishes. The first value is a Unix timestamp. How many seconds between connection and last publish, and approx how many publishes do you see?

If you can, you may gladly paste the pertinent bit of log here.

**Comment by bdleedy** [comment] 2016-12-20 11:35
I will try a sub from outside (I'll have to setup another cert). My hope with turning off wifi is that the change of connection type wouldn't slow or interrupt the traffic. I can capture the log tonight when I open the app.

**Comment by jpmens** [comment] 2016-12-20 11:39
Why do you need another cert? Are you using TLS client certificates?

Also: what version of Mosquitto are you running please?

**Comment by bdleedy** [comment] 2017-01-14 23:26
This problem 'went away' for me for a while but then returned. The problem is now worse. Before, I could open the app and instantly the publishes would go. Now I believe opening the settings is what will 'open the gates'.
From mosquitto log

```
1484435304: OpenSSL Error: error:140890C7:SSL routines:ssl3_get_client_certificate:peer did not return a certificate
1484435305: OpenSSL Error: error:140890C7:SSL routines:ssl3_get_client_certificate:peer did not return a certificate
1484435308: OpenSSL Error: error:140890C7:SSL routines:ssl3_get_client_certificate:peer did not return a certificate
1484435312: OpenSSL Error: error:140890C7:SSL routines:ssl3_get_client_certificate:peer did not return a certificate
```


Then, after opening settings and exiting them... (I assume the first few are before I do this)
```1484435826: OpenSSL Error: error:140890C7:SSL routines:ssl3_get_client_certificate:peer did not return a certificate
1484435827: OpenSSL Error: error:140890C7:SSL routines:ssl3_get_client_certificate:peer did not return a certificate
1484435830: OpenSSL Error: error:140890C7:SSL routines:ssl3_get_client_certificate:peer did not return a certificate
1484435834: OpenSSL Error: error:140890C7:SSL routines:ssl3_get_client_certificate:peer did not return a certificate
1484435835: Sending CONNACK to BLiPhone/iPhone (0, 0)
1484435835: Received PUBLISH from BLiPhone/iPhone (d0, q1, r0, m2, 'owntracks/BLiPhone/iPhone/event', ... (163 bytes))
1484435835: Sending PUBACK to BLiPhone/iPhone (Mid: 2)
1484435835: Sending PUBLISH to OpenHAB2 (d0, q0, r0, m0, 'owntracks/BLiPhone/iPhone/event', ... (163 bytes))
1484435835: Received PUBLISH from BLiPhone/iPhone (d0, q1, r1, m3, 'owntracks/BLiPhone/iPhone', ... (154 bytes))```
That goes on then for all of the backlog.

I am running 1.4.10. Yes, I am using TLS.

**Comment by jpmens** [comment] 2017-01-15 09:19
I asked you whether you're using TLS client certificates; you did not answer the question.

The diagnostics you show indicate you've configured Mosquitto to request a client certificate. Is that so, and have you done so corrrectly? You have possibly erroneously specified `require_certificate true`

**Comment by bdleedy** [comment] 2017-01-15 22:23
I did answer at the bottom that I'm using TLS. I do have ```require_certificate true```
That appears to not be what is needed after rereading the description in the config file. Let me comment that out see how it changes.

**Comment by bdleedy** [comment] 2017-01-15 23:23
Nope, commenting that out just makes the app hang on connecting.

Mosquitto conf
```port 1883
protocol mqtt

#====extra listener====
listener 8883 
protocol mqtt
cafile c:\cert\rootca.pem
certfile c:\cert\openhab.crt
keyfile c:\cert\openhab.key
require_certificate false
use_identity_as_username true

log_dest file c:\mqtt.log
log_type error
log_type warning
log_type debug
connection_messages true
log_timestamp true
allow_anonymous false
password_file mypasswordfile
```

iOS settings
```Mode: Private
Host: myddnsaddress
Port: 8883
Websockets: Off
TLS: On
otrp file and passphrase
Use custom security policy: Off
Authentication: On
MQTT username and password
No secret encryption key

Cert profile installed```

**Comment by scanno** [comment] 2017-07-16 20:20
I have made an owntracks client for a domotica solution called Homey (https://www.athom.com).
This works great for Android devices (both MQTT and HTTP), but iOS users have problems that the enter/leave events are not send. Their settings look good (i.e. name, radius etc all set), but no enter/leave events are received by my app. Just location and waypoints. It does not matter if MQTT or HTTP is used.

**Comment by ckrey** [comment] 2017-07-24 10:48
For now self signed certificates need Custom Security Policy.

I do close this issue now. @scanno please open a separate issue for the Homey integration problem

**Closed by ckrey** 2017-07-24 10:48 UTC
Labels: bug
