### ISSUE TITLE
Notification sound when friend leaving or entering region

### ISSUE THREAD

**Issue by Wildbill-Z** [owntracks/ios#690] opened 2021-12-10 14:58 UTC
Hi,
Owntracks is working fine but I am missing a feature or it is just not working for me. When a friend (or myself) is leaving or entering a region, I get a notification on my Iphone 12 (ios 15). But I get this message completely silent. I just see it when randomly watching on the phone. Would it be possible to play a notification sound when Owntracks is showing such a message? Maybe with the option for the user to select a special sound saved on the phone. Or one sound for enter and another for leaving messages?

Thanks

**Comment by jpmens** [comment] 2021-12-14 13:25
As long as the sounds are optional ... ;-) 
They can then probably be disabled in the iOS notifications panel.

**Comment by Wildbill-Z** [comment] 2021-12-14 13:29
Of sure, this should be optional.  IOs has the option to just show notifications but without sound by just disabling it in the ios notification settings for each app. But if notification with sound would come for Android client also, one option for selecting a sound should be "none".

**Comment by ckrey** [comment] 2021-12-14 13:39
@Wildbill-Z you are right, notifications are silent currently (14.2.2)

The standard notification sound will be activated when
- if the phone itself enters or leaves a region
- if a friend notifies the phone about entering of leaving a region
- if a notification is send via `cmd`

Disabling the sound will be through the iOS notifications settings. 

There will be no specific sounds for entering / leaving or per friend

**Comment by ckrey** [comment] 2021-12-14 15:56
It will be in the app store in the future depending on other enhancements / fixes, internal testing, and the Apple App Store approval process.

**Closed** 2022-02-01 17:12 UTC
Labels: enhancement, fixed

**Comment by Wildbill-Z** [comment] 2022-02-12 10:44
@ckrey Do you have any idea when the new version 16 which was published here on 2022-01-30 will make it into Apple app store? I am not sure if I will be able to compile myself using Xcode on MAC or if I just wait for new version in App store.

**Comment by Wildbill-Z** [comment] 2022-02-12 11:47
Just send you an email from my private account

**Comment by Wildbill-Z** [comment] 2022-02-16 09:00
Beta version is working nearly flawlessly. Automatic switching between move and significant mode as mentioned [HERE](https://github.com/owntracks/ios/issues/683) is just working perfect.
I even get notifications about me or a friend entering or leaving a region onto my Apple Watch, which is very cool, but:
Notifications on phone and watch only seem to work if I'm in move mode. When I'm not at home it is just working perfect, but when I'm at home the app switches to significant mode and from there on I won't get any further notifications until I open my iPhone or most of the times until I open Owntracks app itself. When I leave my home the app is also in background but it is switching correctly to move mode and from there on I get the notifications.
I understand, it has something to do with background mode of an app in iOS and that the app is nearly sleeping when in significant mode and waiting for a region event to get triggered by iOS. In iOS settings I set background activity for Owntracks to on but that doesn't seem to change anything here. Is there something else I can do to get notifications timely even when I'm at home in significant mode or is it just a limitation of iOS which could not bypassed? I mean apps like Telegram or WhatsApp or some other apps like Life360, which I used before Owntracks are able to send notifications even when the App is not opened and the phone is sleeping (display off). But I don't know if they all use iOS Push notifications to get triggered?!

Greetings, Jürgen

**Comment by ckrey** [comment] 2022-02-16 09:26
@Wildbill-Z thanks for the feedback.

Yes, reliable background notifications in iOS always rely on Push Notifications which require a centralized backend.
By design and for privacy, we do not provide a centralized backend. The app picks up notifications when
- location changes significantly
- the device enters or leaves regions (circular or iBeacon)
- using the Background Fetch mechanism of iOS, which kicks typically every 15 minutes but depends on battery level, other applications and is under control of iOS

**Comment by Wildbill-Z** [comment] 2022-02-16 09:34
Thanks, I thought that it would work that way and I prefer to have this extra little piece of privacy by not using any external push notification service. For me it is OK as I have a "backup push service" by using iobroker which gets all the Owntracks data from the MQTT broker and can send me a message via Telegram about any (for me) significant events. But apart from this, Owntracks is just working perfect. 👍
