### ISSUE TITLE
Location report "inregions" inconsistent with "transition" messages

### ISSUE THREAD

**Issue by toggledbits** [owntracks/ios#598] opened 2019-09-04 22:44 UTC
I'm working on a geofencing application. I'm having a problem with consistency between the location message's "inregions" list and transition messages. I use the *inregions* field as a check/update, but that's proving to be really problematic.

Here's an example (I won't post the actual data (yet) for privacy):
1. At home, heading to a nearby grocer. Starting condition: `location` messages coming in fine, reporting "Home" in *inregions*;
1. At 17:42:51 I received a `transition` message stamped 17:42:39 saying I've left the "Home" region. Report trigger field is region state/circular. This seems correct.
1. At 17:42:52 I received a `location` with the same timestamp and location as the previous `transition` message just received, but *inregions* still contains "Home". Uh oh. Report trigger is region state/circular.
1. Over the next 36 seconds of the entire drive, my server receives 3 `location` messages, all with "Home" in *inregions*. The locations are well outside the "Home" region boundary. All have no trigger field.
1. At 17:43:43, arriving at the grocery store, I received the expected `transition` message that I have entered the "Grocery" region. The timestamp is 17:43:25, and trigger code is region/circular.
1.  At 17:43:44, on pace, I receive a `location` message with the timestamp and location same as the `transition` message just received, but still "Home" in *inregions* (not "Grocery"). Trigger code is region/circular.
1. At 17:43:46, I receive a `location` message with new timestamp and location, firmly in the "Grocery" region, but still has "Home" in *inregions* (and "Grocery" is not and has not yet appeared in *inregions*). No report trigger field.
1. At 17:44:03, another `location` message, new location still inside "Grocery" region, but *inregions* again has only "Home". Timestamp is 17:44:01. No report trigger field.
1. At 17:44:07, another `location` message exactly same as prior, except this one says it was timer-triggered.
1. After no updates for nearly five minutes, at 17:49:05 finally the first `location` message with "Grocery" in *inregions* and "Home" removed, timestamp 17:44:01/same timestamp and location as the previous two (incorrect) locations. Report trigger was timer.

Exit from the "Grocery" region then caused a `transition` as expected, but this time all following `location` messages until arriving home seemed correct, with no *inregions* field at all. 

Upon entering the "Home" region at 17:59:33, I got a `transition` message as expected, but every `location` message that followed continued to have *no inregions*, until finally at 18:21:10 a `location` was received with "Home" in *inregions* (now correct). Even a forced push at 18:18:17 did not stimulate it to add "Home" to *inregions*.

So it seems like *inregions* isn't maintaining consistency with transitions.

Edit: Phone was in "Move" mode for this test. Will edit again with app version, but I believe it's latest public as of this writing.

Edit 2: App version 12.0.3/en_US; phone IOS 12.4.1

**Comment by ckrey** [comment] 2019-09-05 08:36
The problem is caused by filtering out "false" positives and negatives as reported in #76 back in 2015.

I will need to review the workaround

**Comment by toggledbits** [comment] 2019-09-05 15:09
OK, I'll trust the expert on this, but in reading #76, it seems to describe a different problem. I'm not getting erroneous/spurious transitions, I'm getting contents of *inregions* that are not consistent with transitions. All of the transitions received in my example above are correct, accurage and timely, and the location accuracy reported in all reports (including locations with bad *inregions*) seems quite good--range 6 to 32 in almost every case.

After more testing, it appears that *inregions* is deeply out of phase somehow. After 5 or more minute, *inregions* comes around to agree with the accrued state of transitions. But there seems to be a very consistent delay between a transition and *inregions* updating to include or exclude that region.

**Comment by ckrey** [comment] 2019-09-06 08:37
You are correct. #76 describes a different problem, but the workaround introduced to solve #76 causes the delays you are reporting

**Comment by ckrey** [comment] 2019-09-14 05:17
Will be in 12.0.9

**Closed by ckrey** 2019-09-14 05:17 UTC
Labels: bug, fixed
