### ISSUE TITLE
Battery usage 25% on iPhone Xr in significant changes mode

### ISSUE THREAD

**Issue by frootmig** [owntracks/ios#562] opened 2019-01-12 17:43 UTC
Hi,
I have an issue with Owntracks battery usage. I set the App to significant changes mode. iOS is reporting a battery usage of 25% in the last 24 hours. It tracked one walk and one drive by car in this time. Is this a normal usage and/or can the battery usage be reduced?

I am using an iPhone Xr with iOS 12.1.2.

**Comment by frootmig** [comment] 2019-01-12 18:44
What is the .OTRC config? I can open the iOS settings (location usage always) or the in app 
I am using mqtts, which seems to be reliable.

**Comment by frootmig** [comment] 2019-01-12 18:48
What is the .OTRC config? I can open the iOS settings (location usage always) or the in app 
I am using mqtts, which seems to be reliable.
I am using the recorderd Docker container with eclipse Mosquitto. I am not sure how to show the version. Docker compose shows these images:
``
      Container              Repository        Tag       Image Id      Size  
-----------------------------------------------------------------------------
owntracks_mosquitto_1    eclipse-mosquitto    latest   339b65318937   4.56 MB
owntracks_otrecorder_1   owntracks/recorder   latest   fb1e3f395406   13.2 MB
``

**Comment by jpmens** [comment] 2019-01-12 18:54
Did you close this issue on purpose?!

**Comment by frootmig** [comment] 2019-01-12 19:01
No, that was my 5yr old :-(

I will add websocket support to my mosquitto config next.

**Comment by jpmens** [comment] 2019-01-12 19:21
What do you want Websocket support for? That has nothing at all to do with your issue.

It would be useful to know whether you are seeing a lot of acitivity server-side; this will be visible in the Mosquitto logs.

**Comment by frootmig** [comment] 2019-01-12 19:51
Don‘t I need this for the HTTP support?

In the log I see entries for my device like this:

mosquitto_1   | 1547319199: Sending CONNACK to vojaVolkersiPhone (1, 0)mosquitto_1   | 1547319199: Received PUBLISH from vojaVolkersiPhone (d0, q1, r1, m2, 'owntracks/voja/Volkers iPhone', ... (188 bytes))
mosquitto_1   | 1547319199: Sending PUBACK to vojaVolkersiPhone (Mid: 2)mosquitto_1   | 1547319199: Sending PUBLISH to vojaVolkersiPhone (d0, q1, r0, m545, 'owntracks/voja/Volkers iPhone', ... (188 bytes))
mosquitto_1   | 1547319199: Received SUBSCRIBE from vojaVolkersiPhone
mosquitto_1   | 1547319199: vojaVolkersiPhone 1 owntracks/+/+mosquitto_1   | 1547319199: Sending SUBACK to vojaVolkersiPhone
mosquitto_1   | 1547319199: Sending PUBLISH to vojaVolkersiPhone (d0, q1, r1, m546, 'owntracks/voja/Volkers iPhone', ... (188 bytes))
mosquitto_1   | 1547319199: Received SUBSCRIBE from vojaVolkersiPhone
mosquitto_1   | 1547319199: vojaVolkersiPhone 1 owntracks/+/+/eventmosquitto_1   | 1547319199: Sending SUBACK to vojaVolkersiPhone
mosquitto_1   | 1547319199: Received SUBSCRIBE from vojaVolkersiPhone
mosquitto_1   | 1547319199: vojaVolkersiPhone 1 owntracks/+/+/infomosquitto_1   | 1547319199: Sending SUBACK to vojaVolkersiPhone
mosquitto_1   | 1547319199: Received SUBSCRIBE from vojaVolkersiPhone
mosquitto_1   | 1547319199: vojaVolkersiPhone 1 owntracks/voja/Volkersmosquitto_1   | 1547319199: Sending SUBACK to vojaVolkersiPhone
mosquitto_1   | 1547319199: Received SUBSCRIBE from vojaVolkersiPhone
mosquitto_1   | 1547319199: vojaVolkersiPhone 1 iPhone/cmdmosquitto_1   | 1547319199: Sending SUBACK to vojaVolkersiPhone
mosquitto_1   | 1547319199: Received PUBACK from vojaVolkersiPhone (Mid: 545)mosquitto_1   | 1547319199: Received PUBACK from vojaVolkersiPhone (Mid: 546)mosquitto_1   | 1547319214: Received DISCONNECT from vojaVolkersiPhone
mosquitto_1   | 1547319214: Client vojaVolkersiPhone disconnected.

Which log entries would be interesting to count? E.g grep for one of them and do a wc -l?

**Comment by jpmens** [comment] 2019-01-12 20:04
> Don‘t I need this for the HTTP support?

This makes no sense if you are using MQTT. Please think about how you want your device to connect to your infrastructure and what you want to do exactly and then decide on the components you need.

I believe this is quite well documented in our Booklet; if you feel there is information missing, please do tell us, and even better, add it for us!

In short:

```
iOS - MQTT - Mosquitto - Recorder

                      or

iOS - HTTP - Recorder
```

These two methods have pro/cons you should be aware of.

**Comment by frootmig** [comment] 2019-01-12 22:16
I used the docker-compose instructions from https://github.com/owntracks/docker-recorder/blob/master/README.md. Both show a mqtt host, I‘ve chosen the variant with mqtt broker. There are no direct instructions for using recorderd without mqtt.

**Comment by jpmens** [comment] 2019-01-13 08:39
Hence my question on why you want HTTP and Websocket support

**Comment by frootmig** [comment] 2019-01-13 09:00
I understand that no HTTP support is needed. mqtts works for tracking.

However, how can I measure if there is a lot of activity on the server side?

**Comment by jpmens** [comment] 2019-01-13 09:04
Follow the logs for, say, 24 hours. Keep an eye on the battery usage of your phone. At the end of 24h, send us the logs to support@owntracks.org

**Comment by frootmig** [comment] 2019-01-14 19:31
That’s wired. Todays battery usage of Owntracks dropped to < 1% and the battery did not exhaust faster than normal.

There are fewer positions recorded than in my last test. On my way there and back the same number per direction.

**Comment by jpmens** [comment] 2019-01-14 20:49
That sounds to me as though you may have had _Move mode_ enabled instead of _Significant changes mode_ you have now...

**Comment by frootmig** [comment] 2019-01-14 21:54
Might be possible. The number of recorded positions point there, too. The only change I am aware of is disabling mqtts mode and then re-enable it.

I am still confused by the mode switching mechanism. Is there a documentation showing the mode and the corresponding icon? Or is it possible to activate a given mode with one click?

**Comment by jpmens** [comment] 2019-01-16 15:32
A description of the mode is shown in the app when the mode is switched.
Closing this as it is not a bug.

**Closed by jpmens** 2019-01-16 15:32 UTC
