### ISSUE TITLE
False beacon not in range detections

### ISSUE THREAD

**Issue by quthla** [owntracks/ios#537] opened 2018-06-08 12:23 UTC
I get a lot false leave notifications followed by an enter notification within a few seconds.

Prefixing the zone name with - wouldn't help too as it's only waiting 3 seconds and would sometimes cause the following enter notification to be supressed making Home Assistant think I left when I actually didn't.

You could start a background thread which only sends the leave notification if beacon was lost for a user defined time interval or something fixed like 30 seconds.

I would submit a PR but my Cocoa is quite bad as I only know Swift.

**Comment by ckrey** [comment] 2018-06-09 08:37
Enter/Leave detection is completely under control of iOS, not the app.

One thing to check would be if the iBeacon you use does follow Apple's specs in terms of signal strength and intervals.

Extending the hold down time to more than a few seconds in background is problematic because iOS limits the background time when woken up by a region event.

@quthla what is the typical time for the region detection to return?

I am not sure if the hold down logic should be done on the phone or in the backend (HA)

**Comment by quthla** [comment] 2018-06-09 11:32
I have set up a Pi 3 to be the beacon.

> @quthla what is the typical time for the region detection to return?
That varies from a few seconds to up to one minute. I built a proxy which delays the leave event for 2 minutes and supresses it if there is an enter event received within that time. That works 100% so far but a fix on app level would be preferred.

> Extending the hold down time to more than a few seconds in background is problematic because iOS limits the background time when woken up by a region event.
I know that but I think you can still extend that time by starting a background thread. Definitely worth a try at least.

**Comment by krambriw** [comment] 2018-09-28 15:27
>I have set up a Pi 3 to be the beacon
I have tested this as well with several Pi3's and it seems to be related to them. With ordinarie iBeacons I don't see this problem with fast leaving/entering

**Comment by saberone** [comment] 2018-11-19 22:46
Anyone figured out why Pi's are so troublesome when being used as an iBeacon. I have the same issue as @quthla  Maybe lowering the transmission power helps?

**Comment by ckrey** [comment] 2019-09-04 13:00
Closing as the problem is probably related to the Raspberry Pi iBeacons, not OwnTracks or iOS

**Closed by ckrey** 2019-09-04 13:00 UTC
Labels: enhancement
